In [1]:
import numpy as np
import pandas as pd

### Matriz de dados $\boldsymbol{X}_{n \times p}$

Seja $\boldsymbol{X}_{4 \times 3} =
        \left[
        \begin{array}{rrr}
        7 & 3 & 9\\
        4 & 6 & 11 \\
        4 & 2 & 5 \\
        5 & 5 & 7\\
        \end{array}
        \right].$

In [2]:
# montar a matriz
X = np.array([[7, 3, 9], [4, 6, 11], [4, 2, 5], [5, 5, 7]])
print(X)

[[ 7  3  9]
 [ 4  6 11]
 [ 4  2  5]
 [ 5  5  7]]

Obter o vetor de médias: $\boldsymbol{\bar{X}}_{p \times 1}$

In [3]:
Xb = np.mean(X, axis=0).reshape(3, 1)
print(Xb)

[[ 5.]
 [ 4.]
 [ 8.]]

Matriz de covariâncias amostrais: $\boldsymbol{S}_{p \times p}$

In [4]:
S = np.cov(X.T)
print(S)

[[ 2.         -0.66666667  0.66666667]
 [-0.66666667  3.33333333  3.33333333]
 [ 0.66666667  3.33333333  6.66666667]]

### Distâncias entre as observações

#### Distância euclidiana

$d_{ij} = \sqrt{\sum_{k=1}^{p} (X_{ik} - X_{jk})^2}$

In [5]:
# usando scipy
from scipy.spatial.distance import squareform, pdist
squareform(pdist(X, metric='euclidean'))

array([[ 0.        ,  4.69041576,  5.09901951,  3.46410162],
       [ 4.69041576,  0.        ,  7.21110255,  4.24264069],
       [ 5.09901951,  7.21110255,  0.        ,  3.74165739],
       [ 3.46410162,  4.24264069,  3.74165739,  0.        ]])

In [6]:
# usando scikit-learn - não será o nosso padrão para distâncias
from sklearn.metrics.pairwise import euclidean_distances
D = euclidean_distances(X, X)
D

array([[ 0.        ,  4.69041576,  5.09901951,  3.46410162],
       [ 4.69041576,  0.        ,  7.21110255,  4.24264069],
       [ 5.09901951,  7.21110255,  0.        ,  3.74165739],
       [ 3.46410162,  4.24264069,  3.74165739,  0.        ]])

Matricialmente:

$d^2_{ij} = (\boldsymbol{X_{i \cdot}} - \boldsymbol{X_{j \cdot}})^T (\boldsymbol{X_{i \cdot}} - \boldsymbol{X_{j \cdot}})$

Obter os vetores $\boldsymbol{X}_{1\cdot}$ $\boldsymbol{X}_{2\cdot}$, $\cdots$

In [7]:
X1p = X[0,:].reshape(3, 1)
X2p = X[1,:].reshape(3, 1)
X3p = X[2,:].reshape(3, 1)
X4p = X[3,:].reshape(3, 1)

In [8]:
# distância entre as observações 1 e 2

In [9]:
# obter as outras: d13, d14, d23, d24

#### Distância euclidiana padronizada

$d_{ij} = \sqrt{\sum_{k=1}^{p}\dfrac{(X_{ik} - X_{jk})^2}{S_{kk}}}$

In [10]:
# usando scipy
squareform(pdist(X, metric='seuclidean'))

array([[ 0.        ,  2.79284801,  2.68328157,  1.94935887],
       [ 2.79284801,  0.        ,  3.19374388,  1.78885438],
       [ 2.68328157,  3.19374388,  0.        ,  1.94935887],
       [ 1.94935887,  1.78885438,  1.94935887,  0.        ]])

Matricialmente:

$d^2_{ij} = (\boldsymbol{X_{i \cdot}} - \boldsymbol{X_{j \cdot}})^T \boldsymbol{D}^{-1} (\boldsymbol{X_{i \cdot}} - \boldsymbol{X_{j \cdot}})$,

em que $\boldsymbol{D}^{-1} = diag(1/S_{ii})$

In [11]:
# D**{-1}

In [12]:
# distância entre as observações 1 e 2

In [14]:
# as outras distâncias

#### Distância de Mahalanobis

$d^2_{ij} = (\boldsymbol{X_{i \cdot}} - \boldsymbol{X_{j \cdot}})^T \boldsymbol{S}^{-1} (\boldsymbol{X_{i \cdot}} - \boldsymbol{X_{j \cdot}})$,

em que $\boldsymbol{S}^{-1}$ é a inversa de $\boldsymbol{S}$

In [15]:
# usando scipy
squareform(pdist(X, metric='mahalanobis'))

array([[ 0.        ,  2.44948974,  2.44948974,  2.44948974],
       [ 2.44948974,  0.        ,  2.44948974,  2.44948974],
       [ 2.44948974,  2.44948974,  0.        ,  2.44948974],
       [ 2.44948974,  2.44948974,  2.44948974,  0.        ]])

In [16]:
# S**{-1}

In [17]:
# distância entre as observações 1 e 2

In [18]:
# as outras distâncias

### Ler um csv (dataframe)

In [19]:
import pandas as pd

In [20]:
# o arquivo '.csv' deve estar na mesma pasta em que este notebook esteja salvo
# se não estiver, o caminho deve ser colocado
medidas = pd.read_csv('medidas.csv')

In [21]:
medidas.head()

   torax  cintura  quadril sexo
0     34       30       32    M
1     37       32       37    M
2     38       30       36    M
3     36       33       39    M
4     38       29       33    M

In [22]:
medidas.mean()

torax      37.00
cintura    28.00
quadril    37.05
dtype: float64

In [23]:
medidas.cov()

            torax    cintura   quadril
torax    6.631579   6.368421  3.000000
cintura  6.368421  12.526316  3.578947
quadril  3.000000   3.578947  5.944737

In [24]:
medidas.corr()

            torax   cintura   quadril
torax    1.000000  0.698734  0.477800
cintura  0.698734  1.000000  0.414741
quadril  0.477800  0.414741  1.000000

### Transformando em matriz

In [25]:
# subselecionar variáveis e transformar em matriz
X = medidas.values[:, 0:3]
# mudar o tipo dos dados
X = np.asarray(X, dtype=float)

In [26]:
n = X.shape[0]

In [27]:
p = X.shape[1]

Obter as matrizes de distâncias (dos três tipos vistos) entre as observações:

In [28]:
# euclidiana
print(squareform(pdist(X, metric='euclidean')))

[[  0.           6.164414     5.65685425   7.87400787   4.24264069  11.
   12.04159458   8.94427191   7.81024968  10.09950494   7.           7.34846923
    7.81024968   8.30662386   7.48331477   7.07106781   7.81024968
    6.70820393   9.16515139   7.68114575]
 [  6.164414     0.           2.44948974   2.44948974   5.09901951
    6.08276253   5.91607978   3.74165739   3.60555128   4.47213595
    8.30662386   7.07106781   8.54400375  11.18033989   6.164414     6.
    7.68114575   6.08276253   5.09901951   9.43398113]
 [  5.65685425   2.44948974   0.           4.69041576   3.16227766
    5.74456265   7.           4.           2.23606798   4.69041576
    6.40312424   5.47722558   7.28010989   9.64365076   4.89897949
    4.24264069   6.70820393   4.58257569   4.47213595   7.68114575]
 [  7.87400787   2.44948974   4.69041576   0.           7.48331477
    7.14142843   5.           3.74165739   5.38516481   5.09901951
    9.8488578    8.24621125   9.43398113  12.4498996    7.07106781
    7.34846923   8.30662386   7.28010989   5.47722558  10.81665383]
 [  4.24264069   5.09901951   3.16227766   7.48331477   0.           7.68114575
   10.04987562   7.07106781   4.58257569   7.34846923   5.74456265   6.
    7.54983444   8.66025404   6.164414     5.09901951   7.54983444
    5.38516481   7.07106781   7.        ]
 [ 11.           6.08276253   5.74456265   7.14142843   7.68114575   0.
    5.09901951   5.74456265   3.74165739   2.23606798  11.04536102
    9.94987437  12.08304597  14.69693846   9.21954446   8.54400375
   11.40175425   9.2736185    6.70820393  12.40967365]
 [ 12.04159458   5.91607978   7.           5.          10.04987562
    5.09901951   0.           4.12310563   5.83095189   3.31662479
   12.08304597  10.24695077  11.91637529  15.29705854   9.           9.11043358
   10.77032961   9.48683298   5.74456265  13.19090596]
 [  8.94427191   3.74165739   4.           3.74165739   7.07106781
    5.74456265   4.12310563   0.           3.60555128   3.74165739
    8.06225775   6.164414     7.81024968  11.18033989   4.89897949
    5.09901951   6.70820393   5.38516481   2.           9.11043358]
 [  7.81024968   3.60555128   2.23606798   5.38516481   4.58257569
    3.74165739   5.83095189   3.60555128   0.           3.           7.48331477
    6.40312424   8.48528137  11.04536102   5.74456265   5.           7.87400787
    5.65685425   4.12310563   8.83176087]
 [ 10.09950494   4.47213595   4.69041576   5.09901951   7.34846923
    2.23606798   3.31662479   3.74165739   3.           0.          10.24695077
    8.83176087  10.81665383  13.74772708   7.87400787   7.48331477
    9.94987437   8.06225775   5.09901951  11.53256259]
 [  7.           8.30662386   6.40312424   9.8488578    5.74456265
   11.04536102  12.08304597   8.06225775   7.48331477  10.24695077   0.
    2.23606798   2.82842712   3.74165739   3.60555128   3.           3.74165739
    2.82842712   6.70820393   1.41421356]
 [  7.34846923   7.07106781   5.47722558   8.24621125   6.           9.94987437
   10.24695077   6.164414     6.40312424   8.83176087   2.23606798   0.
    2.23606798   5.19615242   1.41421356   1.41421356   2.23606798   1.
    4.69041576   3.        ]
 [  7.81024968   8.54400375   7.28010989   9.43398113   7.54983444
   12.08304597  11.91637529   7.81024968   8.48528137  10.81665383
    2.82842712   2.23606798   0.           3.74165739   3.           3.60555128
    1.41421356   2.82842712   6.40312424   2.44948974]
 [  8.30662386  11.18033989   9.64365076  12.4498996    8.66025404
   14.69693846  15.29705854  11.18033989  11.04536102  13.74772708
    3.74165739   5.19615242   3.74165739   0.           6.40312424
    6.40312424   5.09901951   5.83095189   9.8488578    2.44948974]
 [  7.48331477   6.164414     4.89897949   7.07106781   6.164414
    9.21954446   9.           4.89897949   5.74456265   7.87400787
    3.60555128   1.41421356   3.           6.40312424   0.           1.41421356
    2.23606798   1.           3.46410162   4.35889894]
 [  7.07106781   6.           4.24264069   7.34846923   5.09901951
    8.54400375   9.11043358   5.09901951   5.           7.48331477   3.
    1.41421356   3.60555128   6.40312424   1.41421356   0.           3.31662479
    1.           3.74165739   4.12310563]
 [  7.81024968   7.68114575   6.70820393   8.30662386   7.54983444
   11.40175425  10.77032961   6.70820393   7.87400787   9.94987437
    3.74165739   2.23606798   1.41421356   5.09901951   2.23606798
    3.31662479   0.           2.44948974   5.38516481   3.74165739]
 [  6.70820393   6.08276253   4.58257569   7.28010989   5.38516481
    9.2736185    9.48683298   5.38516481   5.65685425   8.06225775
    2.82842712   1.           2.82842712   5.83095189   1.           1.
    2.44948974   0.           4.12310563   3.74165739]
 [  9.16515139   5.09901951   4.47213595   5.47722558   7.07106781
    6.70820393   5.74456265   2.           4.12310563   5.09901951
    6.70820393   4.69041576   6.40312424   9.8488578    3.46410162
    3.74165739   5.38516481   4.12310563   0.           7.68114575]
 [  7.68114575   9.43398113   7.68114575  10.81665383   7.          12.40967365
   13.19090596   9.11043358   8.83176087  11.53256259   1.41421356   3.
    2.44948974   2.44948974   4.35889894   4.12310563   3.74165739
    3.74165739   7.68114575   0.        ]]

In [29]:
D_e = squareform(pdist(X, metric='euclidean'))

In [30]:
D_e[0,1]

6.164414002968976

In [31]:
D_ep = squareform(pdist(X, metric='seuclidean'))
print(D_ep)

[[ 0.          2.42525694  2.25923766  3.09261171  1.63117944  4.31154153
   4.79256312  3.63022368  3.10386405  3.99384549  2.23406992  2.60851942
   2.66070483  2.4357548   2.81713727  2.61531153  2.83752977  2.46695889
   3.67394226  2.36146196]
 [ 2.42525694  0.          0.7989602   0.95052074  1.88699164  2.36575304
   2.37536848  1.40856864  1.29478592  1.75657693  2.4357548   2.01557891
   2.54290907  3.45106301  1.78688535  1.69527272  2.33176405  1.7391789
   1.71524016  2.78252138]
 [ 2.25923766  0.7989602   0.          1.68392584  1.26244848  2.18220831
   2.71614412  1.64056588  0.87828847  1.78617323  1.9092774   1.66348698
   2.33556503  3.09062276  1.59792041  1.26345582  2.2541874   1.4313286
   1.73516112  2.33176405]
 [ 3.09261171  0.95052074  1.68392584  0.          2.81713727  2.76350083
   1.9815758   1.2206056   1.95039737  1.96205841  3.02619281  2.40460138
   2.78252138  3.90156473  2.01989622  2.17610258  2.42500192  2.14117463
   1.66348698  3.29020415]
 [ 1.63117944  1.88699164  1.26244848  2.81713727  0.          2.94851306
   3.93776377  2.88485999  1.83697113  2.85156223  1.808822    2.13820998
   2.66457372  2.80175338  2.35097057  1.88699164  2.80987721  2.00327691
   2.88485999  2.21448787]
 [ 4.31154153  2.36575304  2.18220831  2.76350083  2.94851306  0.
   2.03185413  2.18220831  1.35819241  0.87828847  3.74327087  3.38657196
   4.18231341  5.07484135  3.20356652  2.91045306  4.01572539  3.22971431
   2.39165555  4.19894325]
 [ 4.79256312  2.37536848  2.71614412  1.9815758   3.93776377  2.03185413
   0.          1.41227692  2.21898355  1.32082164  4.137834    3.4245208
   4.01252522  5.27393386  3.00265208  3.07803642  3.63720655  3.24497515
   1.808822    4.4716462 ]
 [ 3.63022368  1.40856864  1.64056588  1.2206056   2.88485999  2.18220831
   1.41227692  0.          1.45503224  1.35819241  2.77173678  2.02803283
   2.60779451  3.8645649   1.59792041  1.71524016  2.2541874   1.84239783
   0.56509091  3.07803642]
 [ 3.10386405  1.29478592  0.87828847  1.95039737  1.83697113  1.35819241
   2.21898355  1.45503224  0.          1.06910499  2.44121119  2.09964205
   2.88140955  3.74327087  1.96423659  1.62310005  2.75546471  1.9209397
   1.56091209  2.89041002]
 [ 3.99384549  1.75657693  1.78617323  1.96205841  2.85156223  0.87828847
   1.32082164  1.35819241  1.06910499  0.          3.40154985  2.89041002
   3.62918678  4.67326305  2.60998216  2.44121119  3.38657196  2.7049316
   1.67411762  3.81921646]
 [ 2.23406992  2.4357548   1.9092774   3.02619281  1.808822    3.74327087
   4.137834    2.77173678  2.44121119  3.40154985  0.          0.86758056
   1.12961883  1.35819241  1.35398373  1.06910499  1.48221144  0.99608826
   2.46695889  0.48023493]
 [ 2.60851942  2.01557891  1.66348698  2.40460138  2.13820998  3.38657196
   3.4245208   2.02803283  2.09964205  2.89041002  0.86758056  0.
   0.82644209  1.89461724  0.49804413  0.48023493  0.87828847  0.28254545
   1.68392584  1.06910499]
 [ 2.66070483  2.54290907  2.33556503  2.78252138  2.66457372  4.18231341
   4.01252522  2.60779451  2.88140955  3.62918678  1.12961883  0.82644209
   0.          1.40856864  1.04437463  1.29478592  0.49804413  0.96046985
   2.28121756  0.95052074]
 [ 2.4357548   3.45106301  3.09062276  3.90156473  2.80175338  5.07484135
   5.27393386  3.8645649   3.74327087  4.67326305  1.35819241  1.89461724
   1.40856864  0.          2.30779336  2.28121756  1.88699164  2.03676165
   3.56364529  0.92261723]
 [ 2.81713727  1.78688535  1.59792041  2.01989622  2.35097057  3.20356652
   3.00265208  1.59792041  1.96423659  2.60998216  1.35398373  0.49804413
   1.04437463  2.30779336  0.          0.56480942  0.82644209  0.41014147
   1.26307816  1.54376982]
 [ 2.61531153  1.69527272  1.26345582  2.17610258  1.88699164  2.91045306
   3.07803642  1.71524016  1.62310005  2.44121119  1.06910499  0.48023493
   1.29478592  2.28121756  0.56480942  0.          1.26696125  0.38832158
   1.40856864  1.41227692]
 [ 2.83752977  2.33176405  2.2541874   2.42500192  2.80987721  4.01572539
   3.63720655  2.2541874   2.75546471  3.38657196  1.48221144  0.87828847
   0.49804413  1.88699164  0.82644209  1.26696125  0.          0.92261723
   1.95039737  1.40856864]
 [ 2.46695889  1.7391789   1.4313286   2.14117463  2.00327691  3.22971431
   3.24497515  1.84239783  1.9209397   2.7049316   0.99608826  0.28254545
   0.96046985  2.03676165  0.41014147  0.38832158  0.92261723  0.
   1.56091209  1.24183137]
 [ 3.67394226  1.71524016  1.73516112  1.66348698  2.88485999  2.39165555
   1.808822    0.56509091  1.56091209  1.67411762  2.46695889  1.68392584
   2.28121756  3.56364529  1.26307816  1.40856864  1.95039737  1.56091209
   0.          2.74924386]
 [ 2.36146196  2.78252138  2.33176405  3.29020415  2.21448787  4.19894325
   4.4716462   3.07803642  2.89041002  3.81921646  0.48023493  1.06910499
   0.95052074  0.92261723  1.54376982  1.41227692  1.40856864  1.24183137
   2.74924386  0.        ]]

In [32]:
D_m = squareform(pdist(X, metric='mahalanobis'))
print(D_m)

[[ 0.          2.13928548  2.49456078  2.95045513  2.46708024  4.54494525
   4.40174893  3.79408126  3.53388606  3.88030456  3.51118975  3.64493416
   3.56364741  3.19027182  3.65702889  3.60813597  3.65963586  3.3243057
   4.25021398  3.55238013]
 [ 2.13928548  0.          1.34196736  1.36431217  2.48625182  3.29685818
   2.27825898  1.82851444  2.28572778  2.19009974  2.83134654  2.47267105
   2.50145396  2.8964389   2.23613781  2.3896208   2.39760686  2.08203459
   2.47024822  2.9059231 ]
 [ 2.49456078  1.34196736  0.          2.62600661  1.41727802  2.23486314
   2.50537469  1.88319337  1.09504987  1.46571875  1.79612024  1.78733444
   2.27908073  2.33412218  1.8576208   1.51559366  2.46077958  1.51140783
   2.13706151  2.03657544]
 [ 2.95045513  1.36431217  2.62600661  0.          3.84155958  4.37525328
   2.29957259  2.11385738  3.43442979  3.09989176  3.82843862  3.20405215
   2.9059231   3.6506118   2.76696874  3.25464932  2.537635    2.82545541
   2.8695104   3.78869392]
 [ 2.46708024  2.48625182  1.41727802  3.84155958  0.          2.48687098
   3.87323612  3.26827952  1.73167109  2.47197296  2.0998174   2.66710787
   3.22977371  2.69090098  2.97047649  2.37549525  3.57025783  2.52501286
   3.37007313  2.42976772]
 [ 4.54494525  3.29685818  2.23486314  4.37525328  2.48687098  0.
   3.01726272  2.90938865  1.22201849  1.34755052  2.76844811  2.91044781
   3.77829567  3.89553483  3.09578812  2.47156775  3.99921897  2.90458684
   2.78080902  3.17023904]
 [ 4.40174893  2.27825898  2.50537469  2.29957259  3.87323612  3.01726272
   0.          0.99839446  2.49896773  1.75371758  3.36348666  2.60227062
   2.80936013  3.80415107  2.17368084  2.5030995   2.53980647  2.40106622
   1.48673173  3.44142399]
 [ 3.79408126  1.82851444  1.88319337  2.11385738  3.26827952  2.90938865
   0.99839446  0.          2.05081915  1.61602462  2.48067386  1.66400455
   1.82810565  2.81293746  1.20206583  1.63743646  1.61958572  1.4323999
   0.79654027  2.5030995 ]
 [ 3.53388606  2.28572778  1.09504987  3.43442979  1.73167109  1.22201849
   2.49896773  2.05081915  0.          0.88060758  1.77202616  1.85812882
   2.66490844  2.76844811  2.04641294  1.42734908  2.90550111  1.77660563
   1.9996706   2.13996386]
 [ 3.88030456  2.19009974  1.46571875  3.09989176  2.47197296  1.34755052
   1.75371758  1.61602462  0.88060758  0.          2.4070246   2.13996386
   2.83222785  3.28190527  2.10323576  1.77202616  2.91044781  2.00698842
   1.70722412  2.69391673]
 [ 3.51118975  2.83134654  1.79612024  3.82843862  2.0998174   2.76844811
   3.36348666  2.48067386  1.77202616  2.4070246   0.          0.9740066
   1.67009722  1.22201849  1.5296184   0.88060758  2.18753396  1.15239386
   2.14366283  0.44415141]
 [ 3.64493416  2.47267105  1.78733444  3.20405215  2.66710787  2.91044781
   2.60227062  1.66400455  1.85812882  2.13996386  0.9740066   0.
   0.93747158  1.39577311  0.57619693  0.44415141  1.34755052  0.39827013
   1.28524938  0.88060758]
 [ 3.56364741  2.50145396  2.27908073  2.9059231   3.22977371  3.77829567
   2.80936013  1.82810565  2.66490844  2.83222785  1.67009722  0.93747158
   0.          1.27788928  0.77834396  1.35306367  0.57619693  0.88830281
   1.6497592   1.36431217]
 [ 3.19027182  2.8964389   2.33412218  3.6506118   2.69090098  3.89553483
   3.80415107  2.81293746  2.76844811  3.28190527  1.22201849  1.39577311
   1.27788928  0.          1.72081135  1.6497592   1.80306591  1.43710538
   2.62271453  0.86247184]
 [ 3.65702889  2.23613781  1.8576208   2.76696874  2.97047649  3.09578812
   2.17368084  1.20206583  2.04641294  2.10323576  1.5296184   0.57619693
   0.77834396  1.72081135  0.          0.83504861  0.93747158  0.47079834
   0.93051541  1.41367623]
 [ 3.60813597  2.3896208   1.51559366  3.25464932  2.37549525  2.47156775
   2.5030995   1.63743646  1.42734908  1.77202616  0.88060758  0.44415141
   1.35306367  1.6497592   0.83504861  0.          1.71343326  0.56697933
   1.27788928  0.99839446]
 [ 3.65963586  2.39760686  2.46077958  2.537635    3.57025783  3.99921897
   2.53980647  1.61958572  2.90550111  2.91044781  2.18753396  1.34755052
   0.57619693  1.80306591  0.93747158  1.71343326  0.          1.20712485
   1.59396829  1.92077979]
 [ 3.3243057   2.08203459  1.51140783  2.82545541  2.52501286  2.90458684
   2.40106622  1.4323999   1.77660563  2.00698842  1.15239386  0.39827013
   0.88830281  1.43710538  0.47079834  0.56697933  1.20712485  0.
   1.2526774   1.09051202]
 [ 4.25021398  2.47024822  2.13706151  2.8695104   3.37007313  2.78080902
   1.48673173  0.79654027  1.9996706   1.70722412  2.14366283  1.28524938
   1.6497592   2.62271453  0.93051541  1.27788928  1.59396829  1.2526774
   0.          2.15364961]
 [ 3.55238013  2.9059231   2.03657544  3.78869392  2.42976772  3.17023904
   3.44142399  2.5030995   2.13996386  2.69391673  0.44415141  0.88060758
   1.36431217  0.86247184  1.41367623  0.99839446  1.92077979  1.09051202
   2.15364961  0.        ]]

### Outro dataframe: imrs.csv

In [33]:
mg = pd.read_csv('imrs.csv')

In [34]:
mg.head()

,ibge7,meso,nome_meso,micro,nome_micro,mun,tx_mort_acid_15_29,tx_mort_hom_15_29,tx_mort_mama,tx_mort_inf,...,rdpc,renocup,perc_rdpc_140,fam_pbf,tx_emp_form,rend_pc_form,pib_pc,perc_agro,perc_serv,tx_ativ_18m
0,3100104,3105,Triângulo Mineiro/Alto Paranaíba,31019,Patrocínio,Abadia dos Dourados,66.53,0.00,0.00,0.00,...,596.18,920.10,7.94,589,22.9,114.28,11744.69,37.90,26.86,65.97
1,3100203,3106,Central Mineira,31024,Três Marias,Abaeté,56.22,0.00,8.73,27.27,...,707.24,930.85,6.69,1428,27.5,172.19,11466.39,22.08,40.06,65.90
2,3100302,3112,Zona da Mata,31061,Manhuaçu,Abre Campo,30.90,0.00,0.00,27.21,...,444.32,685.72,23.33,1293,20.1,117.72,7998.32,45.80,31.92,63.80
3,3100401,3112,Zona da Mata,31060,Ponte Nova,Acaiaca,0.00,0.00,0.00,20.83,...,357.03,646.71,26.53,389,11.7,61.49,6049.45,25.16,41.87,57.71
4,3100500,3108,Vale do Rio Doce,31039,Ipatinga,Açucena,0.00,34.13,0.00,19.61,...,325.42,514.60,30.70,1172,10.3,52.78,5603.93,41.22,29.89,54.21

In [35]:
# selecionar microrregião de Varginha
vgn = mg.query('nome_micro == "Varginha"')
vgn.head()

,ibge7,meso,nome_meso,micro,nome_micro,mun,tx_mort_acid_15_29,tx_mort_hom_15_29,tx_mort_mama,tx_mort_inf,...,rdpc,renocup,perc_rdpc_140,fam_pbf,tx_emp_form,rend_pc_form,pib_pc,perc_agro,perc_serv,tx_ativ_18m
75,3107109,3110,Sul/Sudoeste de Minas,31050,Varginha,Boa Esperança,60.75,19.07,25.98,14.93,...,599.17,903.37,8.43,2835,24.8,140.03,13127.48,28.65,39.28,64.92
117,3110905,3110,Sul/Sudoeste de Minas,31050,Varginha,Campanha,25.91,0.00,13.03,6.21,...,686.16,1021.62,6.55,786,27.3,149.06,10611.67,33.56,29.17,70.14
122,3111309,3110,Sul/Sudoeste de Minas,31050,Varginha,Campo do Meio,0.00,32.32,17.71,26.09,...,472.71,709.35,8.82,1111,18.5,105.89,7836.89,48.22,28.09,67.53
125,3111606,3110,Sul/Sudoeste de Minas,31050,Varginha,Campos Gerais,29.90,26.98,22.16,3.04,...,503.91,744.47,9.73,2422,18.3,93.65,11985.82,57.93,25.34,70.96
150,3113909,3110,Sul/Sudoeste de Minas,31050,Varginha,Carmo da Cachoeira,32.41,0.00,0.00,33.11,...,525.35,822.31,9.56,987,27.7,133.98,11871.57,47.49,26.25,71.98

In [36]:
vgn.shape

(16, 42)

In [37]:
# zerar os índices
vgn = vgn.reset_index().drop('index', axis=1)

In [38]:
# vgn.info()

In [39]:
# selecionar colunas específicas
vgn.iloc[:, [5, 6, 7, 8, 9, 11, 12]]

,mun,tx_mort_acid_15_29,tx_mort_hom_15_29,tx_mort_mama,tx_mort_inf,tx_analf_25m,prop_fund_25m
0,Boa Esperança,60.75,19.07,25.98,14.93,9.6,36.9
1,Campanha,25.91,0.00,13.03,6.21,9.8,39.3
2,Campo do Meio,0.00,32.32,17.71,26.09,12.5,34.7
3,Campos Gerais,29.90,26.98,22.16,3.04,14.1,32.0
4,Carmo da Cachoeira,32.41,0.00,0.00,33.11,12.4,33.4
5,Coqueiral,0.00,0.00,21.47,32.97,10.4,31.5
6,Elói Mendes,31.99,15.38,7.85,16.08,14.0,36.9
7,Guapé,59.26,0.00,15.17,7.94,10.5,30.0
8,Ilicínea,0.00,65.00,17.77,7.14,11.8,31.0
9,Monsenhor Paulo,0.00,0.00,0.00,18.52,13.8,38.1
10,Santana da Vargem,0.00,0.00,0.00,26.32,11.0,36.1
11,São Bento Abade,81.90,0.00,0.00,0.00,16.8,29.7
12,São Tomé das Letras,0.00,0.00,0.00,37.74,16.1,34.4
13,Três Corações,41.71,19.83,16.37,14.40,8.6,50.4
14,Três Pontas,29.26,7.03,14.73,9.60,10.9,42.3
15,Varginha,43.40,6.10,6.30,5.44,5.7,58.7

In [40]:
vgn.columns

Index(['ibge7', 'meso', 'nome_meso', 'micro', 'nome_micro', 'mun',
       'tx_mort_acid_15_29', 'tx_mort_hom_15_29', 'tx_mort_mama',
       'tx_mort_inf', 'existe_conselho_saude', 'tx_analf_25m', 'prop_fund_25m',
       'perc_med_25m', 'tx_med_adeq', 'tx_med_lab', 'existe_conselho_educ',
       'tx_crimes_pat', 'tx_crimes_pes', 'tx_hom', 'existe_uni_infra',
       'perc_energia', 'perc_banagua', 'perc_esgoto', 'perc_lixo', 'pop_total',
       'pop_masc', 'pop_fem', 'raz_dep', 'tx_urb', 'tx_fec', 'esp_vida',
       'rdpc', 'renocup', 'perc_rdpc_140', 'fam_pbf', 'tx_emp_form',
       'rend_pc_form', 'pib_pc', 'perc_agro', 'perc_serv', 'tx_ativ_18m'],
      dtype='object')

In [41]:
# pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.select_dtypes.html
# selecionar apenas as variáveis do tipo float
vgn.select_dtypes(include=['float64'])

,tx_mort_acid_15_29,tx_mort_hom_15_29,tx_mort_mama,tx_mort_inf,tx_analf_25m,prop_fund_25m,perc_med_25m,tx_med_adeq,tx_med_lab,tx_crimes_pat,...,esp_vida,rdpc,renocup,perc_rdpc_140,tx_emp_form,rend_pc_form,pib_pc,perc_agro,perc_serv,tx_ativ_18m
0,60.75,19.07,25.98,14.93,9.6,36.9,23.56,56.4,100.0,25.9,...,76.0,599.17,903.37,8.43,24.8,140.03,13127.48,28.65,39.28,64.92
1,25.91,0.00,13.03,6.21,9.8,39.3,27.33,39.9,79.6,19.4,...,76.0,686.16,1021.62,6.55,27.3,149.06,10611.67,33.56,29.17,70.14
2,0.00,32.32,17.71,26.09,12.5,34.7,23.05,53.5,100.0,61.0,...,75.0,472.71,709.35,8.82,18.5,105.89,7836.89,48.22,28.09,67.53
3,29.90,26.98,22.16,3.04,14.1,32.0,20.41,52.5,100.0,94.2,...,74.0,503.91,744.47,9.73,18.3,93.65,11985.82,57.93,25.34,70.96
4,32.41,0.00,0.00,33.11,12.4,33.4,22.15,34.9,100.0,8.4,...,73.0,525.35,822.31,9.56,27.7,133.98,11871.57,47.49,26.25,71.98
5,0.00,0.00,21.47,32.97,10.4,31.5,21.05,42.8,100.0,32.3,...,75.0,495.77,714.57,13.64,15.1,71.00,11402.89,53.59,24.72,66.81
6,31.99,15.38,7.85,16.08,14.0,36.9,21.83,43.0,100.0,31.7,...,75.0,577.50,921.97,10.46,25.0,155.01,13057.12,31.12,34.04,66.07
7,59.26,0.00,15.17,7.94,10.5,30.0,19.39,53.9,100.0,0.0,...,75.0,487.68,742.73,7.41,18.4,102.09,8945.31,43.65,27.00,66.59
8,0.00,65.00,17.77,7.14,11.8,31.0,17.42,49.0,100.0,26.1,...,75.0,500.79,784.59,6.93,28.5,156.11,9364.19,45.01,22.27,68.14
9,0.00,0.00,0.00,18.52,13.8,38.1,25.87,58.6,100.0,24.5,...,75.0,555.78,854.92,5.17,32.8,194.62,14457.20,40.17,22.52,71.95
10,0.00,0.00,0.00,26.32,11.0,36.1,24.31,44.8,100.0,27.6,...,76.0,553.70,813.53,6.47,28.1,142.50,15154.94,49.45,27.35,74.17
11,81.90,0.00,0.00,0.00,16.8,29.7,14.68,50.9,100.0,21.8,...,73.0,458.65,760.59,9.59,12.4,81.72,9054.98,57.44,18.19,77.10
12,0.00,0.00,0.00,37.74,16.1,34.4,20.74,39.2,100.0,45.0,...,73.0,428.33,648.83,13.48,44.0,239.46,8559.06,23.58,25.52,77.57
13,41.71,19.83,16.37,14.40,8.6,50.4,36.34,58.3,98.6,107.1,...,76.0,749.86,1245.57,8.84,33.8,257.27,24161.24,12.02,42.41,69.23
14,29.26,7.03,14.73,9.60,10.9,42.3,28.21,52.5,100.0,48.2,...,76.0,682.15,1055.69,6.90,30.0,180.56,13712.40,31.21,34.37,71.75
15,43.40,6.10,6.30,5.44,5.7,58.7,42.08,60.6,97.8,56.8,...,77.0,904.57,1382.27,3.83,42.8,344.56,32144.45,5.94,46.41,70.37

In [42]:
# mudando o dataframe para ter só as variáveis float
vgn_num = vgn.select_dtypes(include=['float64'])

In [43]:
vgn_num.shape

(16, 29)

In [44]:
# transformar em matriz pegando apenas as 10 primeiras variáveis
X = vgn_num.values[:, 0:10]
# mudar o tipo dos dados
# X = np.asarray(X, dtype=float)

In [45]:
X.dtype

dtype('float64')

In [46]:
D_e = squareform(pdist(X, metric='euclidean'))

In [48]:
# distância entre Varginha e Elói Mendes - pelo índice
D_e[6, 15]

47.23051026614047

In [49]:
# incluir nomes dos municípios nas distâncias - criar novo dataframe
Dedf = pd.DataFrame(D_e, index=vgn.mun, columns=vgn.mun)

In [50]:
# escolher municípios para saber as distâncias
Dedf.loc['Varginha', 'Elói Mendes']

47.23051026614047

In [51]:
Dedf.loc['Varginha', 'Três Corações']

54.948367582668006

In [54]:
# escolher outros pares de cidades

In [52]:
D_ep = squareform(pdist(X, metric='seuclidean'))
print(D_ep)

[[ 0.          5.15621062  3.2389154   3.43291207  4.69491486  3.60557178
   3.2738831   2.25106606  4.02830969  4.15085194  4.2588054   4.58874396
   5.41663239  4.03979462  2.37725668  5.00000257]
 [ 5.15621062  0.          5.5040704   5.74996729  5.09782209  5.0362405
   4.60873683  4.93865193  5.98512021  5.30458222  4.80553865  6.01474559
   5.77901989  5.91481489  4.51189756  5.97587947]
 [ 3.2389154   5.5040704   0.          2.72007124  4.24662697  2.73403273
   2.74758293  4.06724959  2.94814016  3.17048629  3.15867095  5.29642435
   3.66630133  4.10346613  2.7197381   5.80451962]
 [ 3.43291207  5.74996729  2.72007124  0.          5.39320995  4.23415171
   3.27470301  4.08621652  3.58358667  4.35023508  4.63662309  4.50264622
   4.95782929  4.16511081  3.01617759  6.19102298]
 [ 4.69491486  5.09782209  4.24662697  5.39320995  0.          3.0643241
   2.41411159  3.90426309  5.26600656  3.68675037  2.10152811  4.44968234
   2.32264275  6.22867425  4.01817319  6.70135627]
 [ 3.60557178  5.0362405   2.73403273  4.23415171  3.0643241   0.
   2.94204619  3.68364904  4.40788071  3.7279426   2.56197607  5.52716181
   3.21097332  5.35516615  3.28854604  6.46084781]
 [ 3.2738831   4.60873683  2.74758293  3.27470301  2.41411159  2.94204619
   0.          2.92966941  3.63713698  2.73935617  2.25703724  3.33375475
   2.73908791  4.79781482  2.33952003  5.71222961]
 [ 2.25106606  4.93865193  4.06724959  4.08621652  3.90426309  3.68364904
   2.92966941  0.          4.48013757  3.63357568  3.72040566  3.18362443
   4.96335608  5.4439647   2.91857141  5.81485526]
 [ 4.02830969  5.98512021  2.94814016  3.58358667  5.26600656  4.40788071
   3.63713698  4.48013757  0.          4.72902541  4.63773059  5.54552774
   5.34171957  5.82371799  4.17849177  7.0131219 ]
 [ 4.15085194  5.30458222  3.17048629  4.35023508  3.68675037  3.7279426
   2.73935617  3.63357568  4.72902541  0.          2.16736685  4.28542443
   3.29132736  4.86180011  2.71104139  5.19428904]
 [ 4.2588054   4.80553865  3.15867095  4.63662309  2.10152811  2.56197607
   2.25703724  3.72040566  4.63773059  2.16736685  0.          4.73772206
   2.32266512  5.09057858  2.91362346  5.53042894]
 [ 4.58874396  6.01474559  5.29642435  4.50264622  4.44968234  5.52716181
   3.33375475  3.18362443  5.54552774  4.28542443  4.73772206  0.
   4.92946426  6.60084841  4.39349639  7.1841432 ]
 [ 5.41663239  5.77901989  3.66630133  4.95782929  2.32264275  3.21097332
   2.73908791  4.96335608  5.34171957  3.29132736  2.32266512  4.92946426
   0.          6.17692744  4.27405915  7.20182931]
 [ 4.03979462  5.91481489  4.10346613  4.16511081  6.22867425  5.35516615
   4.79781482  5.4439647   5.82371799  4.86180011  5.09057858  6.60084841
   6.17692744  0.          2.98199008  2.90389579]
 [ 2.37725668  4.51189756  2.7197381   3.01617759  4.01817319  3.28854604
   2.33952003  2.91857141  4.17849177  2.71104139  2.91362346  4.39349639
   4.27405915  2.98199008  0.          3.81969708]
 [ 5.00000257  5.97587947  5.80451962  6.19102298  6.70135627  6.46084781
   5.71222961  5.81485526  7.0131219   5.19428904  5.53042894  7.1841432
   7.20182931  2.90389579  3.81969708  0.        ]]

In [53]:
D_m = squareform(pdist(X, metric='mahalanobis'))
print(D_m)

[[ 0.          5.02039848  3.30928281  5.1767278   4.93351469  3.93390025
   3.81444334  3.46614986  4.74268557  4.95738691  5.1573883   4.47197468
   4.33245553  4.07167026  3.97632966  4.37725311]
 [ 5.02039848  0.          4.67567778  5.13646435  5.32966123  4.9672205
   4.64743563  4.80605996  5.31805228  5.24754401  4.98714698  5.23761037
   4.85004398  4.96389868  4.70439855  5.00282396]
 [ 3.30928281  4.67567778  0.          4.05103     4.51898702  4.01395339
   4.01602647  4.02390272  3.9061566   3.57775865  4.08758481  4.73364817
   3.29002362  3.13313753  4.1804486   4.61032237]
 [ 5.1767278   5.13646435  4.05103     0.          5.08939646  4.46878875
   4.1021185   4.21055201  4.88475715  4.95635616  4.71366742  4.67810908
   4.77962736  3.84687379  3.47526645  5.21305865]
 [ 4.93351469  5.32966123  4.51898702  5.08939646  0.          5.12532865
   3.87637808  4.10963974  5.26118947  5.19973124  4.58722081  5.38182372
   4.54179795  4.59396031  4.60590539  5.06013251]
 [ 3.93390025  4.9672205   4.01395339  4.46878875  5.12532865  0.          4.06993
   3.84365517  5.0516084   5.15665577  3.4867922   5.25533401  3.73991448
   4.70541891  3.45333059  4.76392219]
 [ 3.81444334  4.64743563  4.01602647  4.1021185   3.87637808  4.06993     0.
   4.33335211  3.99236989  4.47397987  4.53700955  4.02165263  3.03986577
   4.40360246  2.21773213  3.85414711]
 [ 3.46614986  4.80605996  4.02390272  4.21055201  4.10963974  3.84365517
   4.33335211  0.          4.7296459   4.15610394  3.77728918  3.9934794
   5.03977599  4.50813478  3.74501807  4.39427257]
 [ 4.74268557  5.31805228  3.9061566   4.88475715  5.26118947  5.0516084
   3.99236989  4.7296459   0.          5.2803616   4.36675226  5.13689978
   4.99397756  5.11483065  4.56764382  4.78641173]
 [ 4.95738691  5.24754401  3.57775865  4.95635616  5.19973124  5.15665577
   4.47397987  4.15610394  5.2803616   0.          4.6034268   5.09139537
   4.36673243  5.07687512  3.9109244   4.63144291]
 [ 5.1573883   4.98714698  4.08758481  4.71366742  4.58722081  3.4867922
   4.53700955  3.77728918  4.36675226  4.6034268   0.          4.35581682
   3.81704288  4.2106279   4.3384126   3.88341457]
 [ 4.47197468  5.23761037  4.73364817  4.67810908  5.38182372  5.25533401
   4.02165263  3.9934794   5.13689978  5.09139537  4.35581682  0.
   4.04534214  4.70163288  4.63149756  4.84447607]
 [ 4.33245553  4.85004398  3.29002362  4.77962736  4.54179795  3.73991448
   3.03986577  5.03977599  4.99397756  4.36673243  3.81704288  4.04534214
   0.          4.1295566   3.96804423  4.66728155]
 [ 4.07167026  4.96389868  3.13313753  3.84687379  4.59396031  4.70541891
   4.40360246  4.50813478  5.11483065  5.07687512  4.2106279   4.70163288
   4.1295566   0.          4.26529402  3.50662658]
 [ 3.97632966  4.70439855  4.1804486   3.47526645  4.60590539  3.45333059
   2.21773213  3.74501807  4.56764382  3.9109244   4.3384126   4.63149756
   3.96804423  4.26529402  0.          3.279055  ]
 [ 4.37725311  5.00282396  4.61032237  5.21305865  5.06013251  4.76392219
   3.85414711  4.39427257  4.78641173  4.63144291  3.88341457  4.84447607
   4.66728155  3.50662658  3.279055    0.        ]]